plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.assertj:assertj-core:3.27.3'
    implementation("io.rest-assured:rest-assured:5.5.6")
}

test {
    useJUnitPlatform()
}

tasks.register('runAllTests') {
    dependsOn test
    doLast {
        println 'All tests have been executed'
    }
}

tasks.register('testRunIsOver') {
    dependsOn 'runAllTests'
    doLast {
        println 'Test run is over'
    }
}

tasks.register('homework3Tests', Test) {
    group = 'my_tests'
    description = 'Run only tests with tag homework3'

    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    outputs.upToDateWhen { false }

    useJUnitPlatform {
        includeTags 'homework3'
    }
}

tasks.register('apiTests', Test) {
    group = 'my_tests'
    description = 'Run only API tests'

    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    outputs.upToDateWhen { false }

    useJUnitPlatform {
        // Запускаем только классы API-тестов
        include '**/GoodsApiTest.class'
        include '**/GoodsApiFullTest.class'
    }
}
